image: node:latest

variables: 
  SKIP_PREFLIGHT_CHECK: "true"
  REACT_APP_WEBSITE_NAME: "OpenSRP"
  REACT_APP_DOMAIN_NAME: "http://localhost:3000"
  REACT_APP_THEME_COLOR: "000000"
  REACT_APP_ENABLE_USERS: "true"
  REACT_APP_ENABLE_ABOUT: "true"
  REACT_APP_DISABLE_LOGIN_PROTECTION: "true"
  REACT_APP_SUPERSET_API_BASE: "https://superset.reveal-stage.smartregister.org/"
  REACT_APP_SUPERSET_API_ENDPOINT: "slice"
  REACT_APP_OPENSRP_CLIENT_ID: "hunter2"
  REACT_APP_OPENSRP_ACCESS_TOKEN_URL: https://reveal-stage.smartregister.org/opensrp/oauth/token
  REACT_APP_OPENSRP_AUTHORIZATION_URL: https://reveal-stage.smartregister.org/opensrp/oauth/authorize
  REACT_APP_OPENSRP_USER_URL: https://reveal-stage.smartregister.org/opensrp/user-details
  REACT_APP_OPENSRP_OAUTH_STATE: opensrp
  REACT_APP_ONADATA_ACCESS_TOKEN_URL: "https://stage-api.ona.io/o/token/"
  REACT_APP_ONADATA_AUTHORIZATION_URL: "https://stage-api.ona.io/o/authorize/"
  REACT_APP_ONADATA_USER_URL: "https://stage-api.ona.io/api/v1/user.json"
  REACT_APP_ONADATA_OAUTH_STATE: "onadata"
  REACT_APP_ONADATA_CLIENT_ID: "hunter2"

stages:
  - build_dependencies
  - lint_test
  - unit_test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build_dependencies
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

lint_testing:
  stage: lint_test
  script: npm run lint-ts 

unit_testing:
  stage: unit_test
  script: npm run test --verbose --coverage=true --forceExit --detectOpenHandles

