name: semantic versioning
on:
  push:
    branches:
      - development

jobs:
  automatically_bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ROBOT_TOKEN }}
      - name: bump
        id: bump
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.ROBOT_TOKEN }}
          git-user-name: road86-robot
          git-user-email: github@chasnelson.co.uk
          output-file: 'false'
      - name: release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.bump.outputs.skipped == 'false' }}
        with:
          tag_name: ${{ steps.bump.outputs.tag }}
          generate_release_notes: 'true'
          prerelease: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.ROBOT_TOKEN }}
